In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
# Load dataset
df = pd.read_csv("../dataset/credit_risk_dataset.csv")

print("Dataset loaded successfully")
print("Dataset shape:", df.shape)

Dataset loaded successfully
Dataset shape: (32581, 30)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   person_age                   32581 non-null  int64
 1   person_income                32581 non-null  int64
 2   person_home_ownership        32581 non-null  str
 3   person_emp_length            31686 non-null  float64
 4   loan_intent                  32581 non-null  str
 5   loan_grade                   32581 non-null  str
 6   loan_amnt                    32581 non-null  int64
 7   loan_int_rate                29465 non-null  float64
 8   loan_status                  32581 non-null  int64
 9   loan_percent_income          32581 non-null  float64
 10  cb_person_default_on_file    32581 non-null  str
 11  cb_person_cred_hist_length   32581 non-null  int64
 12  loan_term_months             32581 non-null  int64
 13  employment_type              31685 non-null  str
 14  education_level              30686 non-null  str
 15  marital_status               31977 non-null  str
 16  num_dependents               31684 non-null  float64
 17  credit_score                 31285 non-null  float64
 18  credit_utilization_pct       31609 non-null  float64
 19  num_open_accounts            31937 non-null  float64
 20  num_late_payments_24m        31602 non-null  float64
 21  num_hard_inquiries_6m        31621 non-null  float64
 22  existing_monthly_debt        30838 non-null  float64
 23  savings_balance              29382 non-null  float64
 24  has_co_applicant             32581 non-null  int64
 25  monthly_income               32581 non-null  float64
 26  est_monthly_payment          29465 non-null  float64
 27  total_interest_cost          29465 non-null  float64
 28  debt_to_income_ratio         27885 non-null  float64
 29  credit_history_to_age_ratio  32581 non-null  float64
dtypes: float64(16), int64(7), str(7)
memory usage: 8.7 MB

In [4]:
# Check duplicates before removal
duplicate_count = df.duplicated().sum()

print("Duplicates before removal:", duplicate_count)

Duplicates before removal: 165

In [5]:
# Remove duplicates
df = df.drop_duplicates()

print("Duplicates removed")
print("New dataset shape:", df.shape)

Duplicates removed
New dataset shape: (32416, 30)

In [6]:
#to handle missing values first, identify numerical and categorical columns
numerical_columns = df.select_dtypes(include=['int64','float64']).columns
categorical_columns = df.select_dtypes(include=['object']).columns

print("Numerical columns:")
print(numerical_columns)

print("\nCategorical columns:")
print(categorical_columns)

Numerical columns:
Index(['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_cred_hist_length', 'loan_term_months', 'num_dependents',
       'credit_score', 'credit_utilization_pct', 'num_open_accounts',
       'num_late_payments_24m', 'num_hard_inquiries_6m',
       'existing_monthly_debt', 'savings_balance', 'has_co_applicant',
       'monthly_income', 'est_monthly_payment', 'total_interest_cost',
       'debt_to_income_ratio', 'credit_history_to_age_ratio'],
      dtype='str')

Categorical columns:
Index(['person_home_ownership', 'loan_intent', 'loan_grade',
       'cb_person_default_on_file', 'employment_type', 'education_level',
       'marital_status'],
      dtype='str')

In [9]:
# Handle missing values correctly

# Numerical columns -> Median
for col in numerical_columns:
    df[col] = df[col].fillna(df[col].median())


# Categorical columns -> Mode
for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])


print("Missing values handled successfully")

Missing values handled successfully

In [10]:
# Check missing values after handling
missing_after = df.isnull().sum()

missing_after[missing_after > 0]

Series([], dtype: int64)

In [12]:
duplicate_count = df.duplicated().sum()

print("Duplicates after removal:", duplicate_count)

Duplicates after removal: 0

In [13]:
#to encode Categorical Variables,first Check categorical columns
categorical_columns

Index(['person_home_ownership', 'loan_intent', 'loan_grade',
       'cb_person_default_on_file', 'employment_type', 'education_level',
       'marital_status'],
      dtype='str')

In [14]:
# Encode categorical variables
label_encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

print("Categorical variables encoded successfully")

Categorical variables encoded successfully

In [15]:
#verrify
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,...,num_late_payments_24m,num_hard_inquiries_6m,existing_monthly_debt,savings_balance,has_co_applicant,monthly_income,est_monthly_payment,total_interest_cost,debt_to_income_ratio,credit_history_to_age_ratio
0,22,59000,3,123.0,4,3,35000,16.02,1,0.59,...,1.0,4.0,331.0,6490.0,0,4916.67,851.50,16090.24,0.241,0.136
1,21,9600,2,5.0,1,1,1000,11.14,0,0.10,...,1.0,1.0,91.0,3004.0,0,800.00,46.67,120.15,0.172,0.095
2,25,9600,0,1.0,3,2,5500,12.87,1,0.57,...,0.0,1.0,235.0,0.0,0,800.00,124.78,1986.57,0.450,0.120
3,23,65500,3,4.0,3,2,35000,15.23,1,0.53,...,1.0,0.0,1171.0,7516.0,0,5458.33,836.88,15212.74,0.368,0.087
4,24,54400,3,8.0,3,2,35000,14.27,1,0.55,...,3.0,1.0,522.0,2538.0,0,4533.33,1200.81,8229.23,0.380,0.167

In [ ]:
# Separate features and target variable(input and output)

X = df.drop('loan_status', axis=1)
y = df['loan_status']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (32416, 29)
Target shape: (32416,)

In [17]:
# Feature scaling
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Feature scaling completed")

Feature scaling completed

In [18]:
# Convert scaled data back to dataframe
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,...,num_late_payments_24m,num_hard_inquiries_6m,existing_monthly_debt,savings_balance,has_co_applicant,monthly_income,est_monthly_payment,total_interest_cost,debt_to_income_ratio,credit_history_to_age_ratio
0,-0.904471,-0.114354,0.923040,28.904903,0.847260,1.524484,4.018287,1.623527,3.929865,2.158065,...,0.686619,2.602241,-0.396337,-0.083624,-0.361632,-0.114354,2.953443,6.206245,0.165686,-0.628669
1,-1.061852,-0.910941,0.225282,0.056504,-0.886007,-0.188909,-1.359219,0.040655,-0.657707,-0.463378,...,0.686619,-0.082518,-0.550037,-0.096332,-0.361632,-0.910941,-1.253087,-0.939712,-0.339342,-1.066805
2,-0.432327,-0.910941,-1.170234,-0.921408,0.269504,0.667787,-0.647491,0.601796,3.742617,-0.463378,...,-0.518245,-0.082518,-0.457817,-0.107283,-0.361632,-0.910941,-0.844837,-0.104566,1.695409,-0.799649
3,-0.747089,-0.009540,0.923040,-0.187974,0.269504,0.667787,4.018287,1.367283,3.368121,-0.463378,...,0.686619,-0.977438,0.141610,-0.079884,-0.361632,-0.009541,2.877030,5.813600,1.095230,-1.152295
4,-0.589708,-0.188530,0.923040,0.789938,0.269504,0.667787,4.018287,1.055898,3.555369,2.158065,...,3.096346,-0.082518,-0.274018,-0.098031,-0.361632,-0.188531,4.779149,2.688767,1.183061,-0.297396

In [19]:
from sklearn.model_selection import train_test_split

# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (25932, 29)
Testing data shape: (6484, 29)